import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ReactMarkdown } from "react-markdown/lib/react-markdown";
import remarkGfm from "remark-gfm";

const Home: NextPage = () => {
  const [inputPrompt, setInputPrompt] = useState("");
  const [result, setResult] = useState("");

  async function onSubmit(event: any) {
    event.preventDefault();
    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt: inputPrompt }),
      });

      const data = await response.json();
      if (response.status !== 200) {
        throw (
          data.error ||
          new Error(`Request failed with status ${response.status}`)
        );
      }
      const regex = /\\n|\\r\\n|\\n\\r|\\r/g;
      setResult(data.result.replace(regex, "<br>"));
      // setInputPrompt("");
    } catch (error: any) {
      // Consider implementing your own error handling logic here
      console.error(error);
      alert(error.message);
    }
  }

  console.log("result: ", result);
  return (
    <>
      <Head>
        <title>Simple GPT Test Bench</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-screen justify-center" data-theme="light">
        <div className="w-1/2 p-4">
          <h3 className="text-2xl">Answer my question</h3>
          <br />
          <form className="flex items-center space-x-4">
            <textarea
              className="textarea-secondary textarea w-full"
              name="prompt"
              placeholder=""
              value={inputPrompt}
              onChange={(e) => setInputPrompt(e.target.value)}
            ></textarea>
            <button className="btn" onClick={onSubmit}>
              Submit
            </button>
          </form>
          <br />
          <div className="font-bold">
          Answer:
          </div>
          <div className="bg-slate-300 p-4 rounded">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
            >
              {result}
            </ReactMarkdown>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
